package utils;

import java.io.BufferedReader;
import java.io.FileInputStream;
import java.io.InputStreamReader;
import java.util.HashMap;

// parse the cluster file generated by kmeans
public class WordClusterReader {
	private HashMap<String, String> map; // key is word, value is class
	
	public WordClusterReader(String file) {
		map = new HashMap<String,String>();
		
		try {
			BufferedReader reader = new BufferedReader(new InputStreamReader(new FileInputStream(file), "utf-8"));
			String thisLine = null;
			Integer cluster = 0;
			while ((thisLine = reader.readLine()) != null) {
				if(thisLine.isEmpty()) {// cluster delimiter
					cluster++;
				} else {
					if(thisLine.indexOf("##the")!=-1) {
						
					} else {
						String[] words = thisLine.split(" ");
						for(int i=0;i<words.length;i++) {
							map.put(words[i], cluster.toString());
						}
					}
				}

			}
			reader.close();
		} catch (Exception e) {
			e.printStackTrace();
		}
	}
	
	public String getCluster(String word) {
		return map.get(word);
	}
}
